// Generated by CoffeeScript 1.3.3
var App;

App = Ember.Application.create();

App.entries = Ember.ArrayController.create({
  content: [
    Ember.Object.create({
      id: 1,
      body: 'hoge'
    }), Ember.Object.create({
      id: 2,
      body: 'moge'
    }), Ember.Object.create({
      id: 3,
      body: 'koge'
    })
  ]
});

App.ApplicationView = Ember.View.extend();

App.EntriesView = Ember.View.extend({
  templateName: 'entries',
  entriesBinding: 'App.entries.content'
});

App.EntryView = Ember.View.extend({
  templateName: 'entry',
  alert: (function() {
    return alert(this.get('content').get('body'));
  }),
  content: null
});
